# creation rules are evaluated sequentially, the first match wins
creation_rules:
     # upon creation of a file that matches the pattern *.dev.yaml,
     #KMS set A is used
     - kms: "arn:aws:kms:us-east-1:378842471989:key/7cd0af20-76f1-45f3-bc8a-5cea34a085f1"